sudo: false

language: c

matrix:
  include:
    - os: linux
      addons:
        apt:
          # http://apt.llvm.org/
          sources: [ubuntu-toolchain-r-test, llvm-toolchain-precise-3.9]
          packages: [libboost-dev, libblocksruntime-dev, libclang-3.9-dev, clang-3.9, clang-tidy-3.9 miniupnpc]
      before_script:
        - export PATH="/usr/lib/llvm-3.9/bin:$PATH"
    - os: osx
      osx_image: xcode8.3
      before_script:
        - brew update
        - brew outdated libffi || brew upgrade libffi
        - brew install boost-build
        - brew install llvm --with-clang --with-clang-extra-tools -v
        - brew install miniupnpc
          # Set path to clang-tidy
        - export PATH="/usr/local/opt/llvm/bin:$PATH"
          # Set path to stdbuf and gtimeout
        - export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"

install:
  - pip install --user codecov

script:
  - clang -v
  - clang-tidy -version
  - ./build.sh
  - ./test.sh
  - for f in *.c; do gcov -n -o . $f; done
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
