sudo: required

language: generic

matrix:
  include:
    - os: linux
      dist: trusty
      before_script:
        - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" | sudo tee -a /etc/apt/sources.list > /dev/null
        - sudo apt-get update -qq
        - sudo apt-get install libboost-dev libblocksruntime-dev libc++-dev clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
    - os: osx
      before_script:
        - brew install boost-build

install:
  - sudo pip install codecov

script:
  - clang -v
  - ./build.sh
  - ./test.sh
  - for f in *.c; do gcov -n -o . $f; done
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
