sudo: require

language: c
compiler: clang

matrix:
  include:
    - os: linux
      dist: trusty
      before_script:
        - sudo apt-get update -qq
        - sudo apt-get install libboost-dev libblocksruntime-dev libc++-dev
    - os: osx
      before_script:
        - brew install boost-build

install:
  - sudo pip install codecov

script:
  - clang -v
  - ./build.sh
  - ./test.sh
  - for f in *.c; do gcov -n -o . $f; done
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
